name: Sync Upstream

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/coleam00/mcp-crawl4ai-rag.git
        git fetch upstream
    
    - name: Check for upstream changes
      id: check
      run: |
        UPSTREAM_SHA=$(git rev-parse upstream/main)
        CURRENT_SHA=$(git rev-parse main)
        
        if [ "$UPSTREAM_SHA" != "$CURRENT_SHA" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "upstream_sha=$UPSTREAM_SHA" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Sync main branch
      if: steps.check.outputs.changes == 'true'
      run: |
        git checkout main
        git merge upstream/main --no-edit
        git push origin main
    
    - name: Sync custom feature branch
      if: steps.check.outputs.changes == 'true'
      run: |
        if git checkout feature/custom-database 2>/dev/null; then
          if git merge main --no-commit --no-ff; then
            git commit -m "Auto-sync: Merge upstream changes into custom-database branch"
            git push origin feature/custom-database
          else
            git merge --abort
            echo "CONFLICTS_DETECTED=true" >> $GITHUB_ENV
          fi
        else
          echo "Feature branch not found, skipping"
        fi
    
    - name: Create issue for manual conflict resolution
      if: env.CONFLICTS_DETECTED == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🔄 Manual merge required: Upstream sync conflicts',
            body: `
            ## Upstream Sync Conflict Detected
            
            The automated upstream sync detected conflicts when trying to merge changes into the \`feature/custom-database\` branch.
            
            **Upstream commit:** ${{ steps.check.outputs.upstream_sha }}
            
            ### Manual Resolution Required:
            \`\`\`bash
            git checkout feature/custom-database
            git merge main
            # Resolve conflicts manually
            git commit
            git push origin feature/custom-database
            \`\`\`
            
            This issue will be automatically closed when the conflicts are resolved.
            `,
            labels: ['sync-conflict', 'manual-action-required']
          })